/** @type {import('tailwindcss').Config} */
module.exports = {
    darkMode: 'class',
    content: [
        "./assets/**/*.js",
        "./templates/**/*.html.twig",
    ],
    safelist: [
        "bg-gradient-to-r",
        "from-gray-200",
        "from-pink-200",
        "from-rose-200",
        "from-red-200",
        "from-orange-200",
        "from-yellow-200",
        "from-lime-200",
        "from-green-200",
        "from-emerald-200",
        "from-teal-200",
        "from-cyan-200",
        "from-sky-200",
        "from-blue-200",
        "from-indigo-200",
        "from-purple-200",
        "from-fuchsia-200",
        "dark:from-gray-900",
        "dark:from-pink-900",
        "dark:from-rose-900",
        "dark:from-red-900",
        "dark:from-orange-900",
        "dark:from-yellow-900",
        "dark:from-lime-900",
        "dark:from-green-900",
        "dark:from-emerald-900",
        "dark:from-teal-900",
        "dark:from-cyan-900",
        "dark:from-sky-900",
        "dark:from-blue-900",
        "dark:from-indigo-900",
        "dark:from-purple-900",
        "dark:from-fuchsia-900",
        "to-gray-50",
        "to-pink-50",
        "to-rose-50",
        "to-red-50",
        "to-orange-50",
        "to-yellow-50",
        "to-lime-50",
        "to-green-50",
        "to-emerald-50",
        "to-teal-50",
        "to-cyan-50",
        "to-sky-50",
        "to-blue-50",
        "to-indigo-50",
        "to-purple-50",
        "to-fuchsia-50",
        "dark:to-gray-700",
        "dark:to-pink-700",
        "dark:to-rose-700",
        "dark:to-red-700",
        "dark:to-orange-700",
        "dark:to-yellow-700",
        "dark:to-lime-700",
        "dark:to-green-700",
        "dark:to-emerald-700",
        "dark:to-teal-700",
        "dark:to-cyan-700",
        "dark:to-sky-700",
        "dark:to-blue-700",
        "dark:to-indigo-700",
        "dark:to-purple-700",
        "dark:to-fuchsia-700"
    ],
    theme: {
        extend: {},
    },
    plugins: []
}
